### ISSUE TITLE
Toolbar icons don't show up

### ISSUE THREAD

**Issue by excelerondesign** [modxcms/fred-rte-tinymce#14]
I can't tell if this is an issue with the plugin or what, but maybe someone else will run into this issue and might find it useful.

The `.mce-ico` class holds the reference the the icon font, so the `:before` pseudo-element naturally inherits the font-family. I had needed to apply a font to all elements in the css, so I added a blanket `*` rule (I know probably not best practice). This got rid of the icons inside the floating tool bar, so I found a cheap easy solution.

I fixed it by adding:
```css
/** included just as an example **/
*,
*::after,
*::before {
    font-family: 'San Francisco', -apple-system, system-ui, BlinkMacSystemFont, Roboto, Helvetica Neue, arial, helvetica, sans-serif;
}
.mce-ico::before {
    font-family: inherit;
}
```

Like I said, don't know if this is a modx issue to fix or just a side effect of someone else's code. Hopefully this helps someone in the future! 😄
